apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-win10
  namespace: testnamespace
spec:
  running: false
  template:
    metadata:
      labels:
        vm: win10
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: harddrive
            bootOrder: 1
          interfaces:
          - masquerade: {}
            model: e1000
            name: default  
        machine:
          type: q35
        resources:
          requests:
            memory: 2G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: win10base
